### ISSUE TITLE
无插件版在WSL中无法正确显示箭头

### ISSUE THREAD

**Issue by wtbxsjy** [chenxuan520/vim-fast#2]
chenxuan你好，首先感谢你的分享，非常好的vim插件整理
但是我在WSL（Ubuntu 22.04 LTS）中测试的时候发现无法显示箭头图标，截图如下
![image](https://user-images.githubusercontent.com/9799980/217191694-1307c346-d6c1-42f8-a4c4-0f1ec0eb1554.png)
请问是否有额外的依赖？

**Comment by chenxuan520** [comment]
这个是字体的设置，你可以直接在vimrc把这几个箭头删掉，这样比较简单

**Comment by chenxuan520** [comment]
直接打开.vimrc,把设置中错误显示的字符(通常是□或者其他非ascii字符)删掉就好了，箭头就会消失

**Comment by wtbxsjy** [comment]
能否帮忙定位一下大概是哪个部分的问题？我试着翻一下没有找到具体的位置

**Comment by chenxuan520** [comment]
在tabline和statusline部分
set statusline+=%4*%{g:status_git_branch}\ %F\ %m%r%h%w%=
类似这一行，你把里面不可见字符搜索一下全部替换成空格就可以了。抱歉，下次提交我就把这个字符删除😊

**Comment by chenxuan520** [comment]
已经删除该字符，:UpdateSelf 可获取最新版本😄
