### ISSUE TITLE
Not support platform type: Darwin

### ISSUE THREAD

**Issue by Priest2wyw** [chenxuan520/vim-fast#3]
when I run `install.sh` in macbook,  there is not support plattform, please help me.

```shell
$ ./install.sh

Not support platform type: Darwin
Not support platform type: Darwin
It takes 0 minutes.
```

**Comment by chenxuan520** [comment]
I'm so sorry. I also want to support the mac platform, but I do not have the money to buy a mac computer, so I can not test the mac. You can use Vimplus.

**Comment by Priest2wyw** [comment]
> I'm so sorry. I also want to support the mac platform, but I do not have the money to buy a mac computer, so I can not test the mac. You can use Vimplus.

I try to move this repo to MacOS. Are there any other script, which should be modified, except `install.sh`?

**Comment by chenxuan520** [comment]
Also the nodejs.sh install script under the shell folder needs to be tested to see if it's a mac system. There should be nothing else, thank you very much!

**Comment by chenxuan520** [comment]
Mac system is already in experimental support, welcome to experience!
